# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Protobuf/Enum/Retcode.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'Protobuf/Enum/Retcode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bProtobuf/Enum/Retcode.proto\x12 ClassIsland.Shared.Protobuf.Enum*v\n\x07Retcode\x12\x08\n\x04None\x10\x00\x12\x0c\n\x07Success\x10\xc8\x01\x12\x18\n\x13ServerInternalError\x10\xf4\x03\x12\x13\n\x0eInvalidRequest\x10\x94\x03\x12\x0f\n\nRegistered\x10\x91N\x12\x13\n\x0e\x43lientNotFound\x10\x92NB#\xaa\x02 ClassIsland.Shared.Protobuf.Enumb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protobuf.Enum.Retcode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002 ClassIsland.Shared.Protobuf.Enum'
  _globals['_RETCODE']._serialized_start=65
  _globals['_RETCODE']._serialized_end=183
# @@protoc_insertion_point(module_scope)
