# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Protobuf/Service/ClientCommandDeliver.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'Protobuf/Service/ClientCommandDeliver.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Protobuf.Server import ClientCommandDeliverScRsp_pb2 as Protobuf_dot_Server_dot_ClientCommandDeliverScRsp__pb2
from Protobuf.Client import ClientCommandDeliverScReq_pb2 as Protobuf_dot_Client_dot_ClientCommandDeliverScReq__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+Protobuf/Service/ClientCommandDeliver.proto\x12#ClassIsland.Shared.Protobuf.Service\x1a/Protobuf/Server/ClientCommandDeliverScRsp.proto\x1a/Protobuf/Client/ClientCommandDeliverScReq.proto2\xaa\x01\n\x14\x43lientCommandDeliver\x12\x91\x01\n\rListenCommand\x12=.ClassIsland.Shared.Protobuf.Client.ClientCommandDeliverScReq\x1a=.ClassIsland.Shared.Protobuf.Server.ClientCommandDeliverScRsp(\x01\x30\x01\x42&\xaa\x02#ClassIsland.Shared.Protobuf.Serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protobuf.Service.ClientCommandDeliver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002#ClassIsland.Shared.Protobuf.Service'
  _globals['_CLIENTCOMMANDDELIVER']._serialized_start=183
  _globals['_CLIENTCOMMANDDELIVER']._serialized_end=353
# @@protoc_insertion_point(module_scope)
