# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Protobuf/Server/ClientCommandDeliverScRsp.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'Protobuf/Server/ClientCommandDeliverScRsp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Protobuf.Enum import CommandTypes_pb2 as Protobuf_dot_Enum_dot_CommandTypes__pb2
from Protobuf.Enum import Retcode_pb2 as Protobuf_dot_Enum_dot_Retcode__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/Protobuf/Server/ClientCommandDeliverScRsp.proto\x12\"ClassIsland.Shared.Protobuf.Server\x1a Protobuf/Enum/CommandTypes.proto\x1a\x1bProtobuf/Enum/Retcode.proto\"\xa6\x01\n\x19\x43lientCommandDeliverScRsp\x12:\n\x07RetCode\x18\x01 \x01(\x0e\x32).ClassIsland.Shared.Protobuf.Enum.Retcode\x12<\n\x04Type\x18\x02 \x01(\x0e\x32..ClassIsland.Shared.Protobuf.Enum.CommandTypes\x12\x0f\n\x07Payload\x18\x03 \x01(\x0c\x42%\xaa\x02\"ClassIsland.Shared.Protobuf.Serverb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protobuf.Server.ClientCommandDeliverScRsp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\"ClassIsland.Shared.Protobuf.Server'
  _globals['_CLIENTCOMMANDDELIVERSCRSP']._serialized_start=151
  _globals['_CLIENTCOMMANDDELIVERSCRSP']._serialized_end=317
# @@protoc_insertion_point(module_scope)
