# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Protobuf/Server/ClientRegisterScRsp.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'Protobuf/Server/ClientRegisterScRsp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Protobuf.Enum import Retcode_pb2 as Protobuf_dot_Enum_dot_Retcode__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)Protobuf/Server/ClientRegisterScRsp.proto\x12\"ClassIsland.Shared.Protobuf.Server\x1a\x1bProtobuf/Enum/Retcode.proto\"b\n\x13\x43lientRegisterScRsp\x12:\n\x07Retcode\x18\x01 \x01(\x0e\x32).ClassIsland.Shared.Protobuf.Enum.Retcode\x12\x0f\n\x07Message\x18\x02 \x01(\tB%\xaa\x02\"ClassIsland.Shared.Protobuf.Serverb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protobuf.Server.ClientRegisterScRsp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\"ClassIsland.Shared.Protobuf.Server'
  _globals['_CLIENTREGISTERSCRSP']._serialized_start=110
  _globals['_CLIENTREGISTERSCRSP']._serialized_end=208
# @@protoc_insertion_point(module_scope)
