# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from Protobuf.Client import ClientRegisterCsReq_pb2 as Protobuf_dot_Client_dot_ClientRegisterCsReq__pb2
from Protobuf.Server import ClientRegisterScRsp_pb2 as Protobuf_dot_Server_dot_ClientRegisterScRsp__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in Protobuf/Service/ClientRegister_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientRegisterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/ClassIsland.Shared.Protobuf.Service.ClientRegister/Register',
                request_serializer=Protobuf_dot_Client_dot_ClientRegisterCsReq__pb2.ClientRegisterCsReq.SerializeToString,
                response_deserializer=Protobuf_dot_Server_dot_ClientRegisterScRsp__pb2.ClientRegisterScRsp.FromString,
                _registered_method=True)
        self.UnRegister = channel.unary_unary(
                '/ClassIsland.Shared.Protobuf.Service.ClientRegister/UnRegister',
                request_serializer=Protobuf_dot_Client_dot_ClientRegisterCsReq__pb2.ClientRegisterCsReq.SerializeToString,
                response_deserializer=Protobuf_dot_Server_dot_ClientRegisterScRsp__pb2.ClientRegisterScRsp.FromString,
                _registered_method=True)


class ClientRegisterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnRegister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientRegisterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=Protobuf_dot_Client_dot_ClientRegisterCsReq__pb2.ClientRegisterCsReq.FromString,
                    response_serializer=Protobuf_dot_Server_dot_ClientRegisterScRsp__pb2.ClientRegisterScRsp.SerializeToString,
            ),
            'UnRegister': grpc.unary_unary_rpc_method_handler(
                    servicer.UnRegister,
                    request_deserializer=Protobuf_dot_Client_dot_ClientRegisterCsReq__pb2.ClientRegisterCsReq.FromString,
                    response_serializer=Protobuf_dot_Server_dot_ClientRegisterScRsp__pb2.ClientRegisterScRsp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ClassIsland.Shared.Protobuf.Service.ClientRegister', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ClassIsland.Shared.Protobuf.Service.ClientRegister', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientRegister(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ClassIsland.Shared.Protobuf.Service.ClientRegister/Register',
            Protobuf_dot_Client_dot_ClientRegisterCsReq__pb2.ClientRegisterCsReq.SerializeToString,
            Protobuf_dot_Server_dot_ClientRegisterScRsp__pb2.ClientRegisterScRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnRegister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ClassIsland.Shared.Protobuf.Service.ClientRegister/UnRegister',
            Protobuf_dot_Client_dot_ClientRegisterCsReq__pb2.ClientRegisterCsReq.SerializeToString,
            Protobuf_dot_Server_dot_ClientRegisterScRsp__pb2.ClientRegisterScRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
