# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Protobuf/Service/ClientRegister.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'Protobuf/Service/ClientRegister.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Protobuf.Client import ClientRegisterCsReq_pb2 as Protobuf_dot_Client_dot_ClientRegisterCsReq__pb2
from Protobuf.Server import ClientRegisterScRsp_pb2 as Protobuf_dot_Server_dot_ClientRegisterScRsp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%Protobuf/Service/ClientRegister.proto\x12#ClassIsland.Shared.Protobuf.Service\x1a)Protobuf/Client/ClientRegisterCsReq.proto\x1a)Protobuf/Server/ClientRegisterScRsp.proto2\x8e\x02\n\x0e\x43lientRegister\x12|\n\x08Register\x12\x37.ClassIsland.Shared.Protobuf.Client.ClientRegisterCsReq\x1a\x37.ClassIsland.Shared.Protobuf.Server.ClientRegisterScRsp\x12~\n\nUnRegister\x12\x37.ClassIsland.Shared.Protobuf.Client.ClientRegisterCsReq\x1a\x37.ClassIsland.Shared.Protobuf.Server.ClientRegisterScRspB&\xaa\x02#ClassIsland.Shared.Protobuf.Serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protobuf.Service.ClientRegister_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002#ClassIsland.Shared.Protobuf.Service'
  _globals['_CLIENTREGISTER']._serialized_start=165
  _globals['_CLIENTREGISTER']._serialized_end=435
# @@protoc_insertion_point(module_scope)
