# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Protobuf/Command/SendNotification.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'Protobuf/Command/SendNotification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'Protobuf/Command/SendNotification.proto\x12#ClassIsland.Shared.Protobuf.Command\"\x93\x02\n\x10SendNotification\x12\x13\n\x0bMessageMask\x18\x01 \x01(\t\x12\x16\n\x0eMessageContent\x18\x02 \x01(\t\x12\x17\n\x0fOverlayIconLeft\x18\x03 \x01(\x05\x12\x18\n\x10OverlayIconRight\x18\x04 \x01(\x05\x12\x13\n\x0bIsEmergency\x18\x05 \x01(\x08\x12\x17\n\x0fIsSpeechEnabled\x18\x06 \x01(\x08\x12\x17\n\x0fIsEffectEnabled\x18\x07 \x01(\x08\x12\x16\n\x0eIsSoundEnabled\x18\x08 \x01(\x08\x12\x11\n\tIsTopmost\x18\t \x01(\x08\x12\x17\n\x0f\x44urationSeconds\x18\n \x01(\x01\x12\x14\n\x0cRepeatCounts\x18\x0b \x01(\x05\x42&\xaa\x02#ClassIsland.Shared.Protobuf.Commandb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protobuf.Command.SendNotification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002#ClassIsland.Shared.Protobuf.Command'
  _globals['_SENDNOTIFICATION']._serialized_start=81
  _globals['_SENDNOTIFICATION']._serialized_end=356
# @@protoc_insertion_point(module_scope)
